### ISSUE TITLE
No Sources option for Window/Desktop

### ISSUE THREAD

**Issue by asim-vax** [lutris/ffmpeg-nvenc#4]
OS: Ubuntu 16.04

Had to do "Installing the libx264-dev package is a workaround but it shouldn't be needed, we already provide it from our script"

But now when I launch OBS there is no option for window or desktop capture, unlike if I just installed ffmpeg & OBS through CLI

**Comment by tenten8401** [comment]
Can confirm this is an issue

**Comment by strycore** [comment]
I added some dependencies to the build script, can someone confirm this fixes the issue?

**Comment by tenten8401** [comment]
This does fix the issue! Thank you very much!

Edit: Have tested and can confirm that it does record properly, at much higher frame-rates than software.

**Comment by strycore** [comment]
Great! :D
