### ISSUE TITLE
libx264 failed to compile on ubuntu 16.10

### ISSUE THREAD

**Issue by spider623** [lutris/ffmpeg-nvenc#5]
i downloaded the scrip and even did the extra mile to get the newer codecs from nvidia but when the time comes to compile x264 it fails, attaching log file of the build, ignore the nvidia codec part, it's a dummy address.

Part of the terminal messages that are not in the log:

`Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/simos/.wget-hsts'. HSTS will be disabled.
--2016-10-29 04:52:18--  http://developer.download.nvidia.com/designworks/video-codec-sdk/secure/7.0/02/Video_Codec_SDK_7.0.1.zip?autho=1477633173_e636809b4d2fd0de7a35cb387bd87669&file=Video_Codec_SDK_7.0.1.zip
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 213.140.213.176, 213.140.213.169
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|213.140.213.176|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 252 [text/html]
Saving to: ‘Video_Codec_SDK_7.0.1.zip?autho=1477633173_e636809b4d2fd0de7a35cb387bd87669&file=Video_Codec_SDK_7.0.1.zip.3’

Video_Codec_SDK_7.0.1.zip?autho=1477633173_e636809b4d2fd0de 100%[=========================================================================================================================================>]     252  --.-KB/s    in 0s      

2016-10-29 04:52:19 (20,6 MB/s) - ‘Video_Codec_SDK_7.0.1.zip?autho=1477633173_e636809b4d2fd0de7a35cb387bd87669&file=Video_Codec_SDK_7.0.1.zip.3’ saved [252/252]

replace Video_Codec_SDK_7.0.1/doc/NVDEC_DA-06209-001_v08.pdf? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/simos/.wget-hsts'. HSTS will be disabled.
--2016-10-29 04:52:24--  http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
Resolving www.tortall.net (www.tortall.net)... 69.55.226.36
Connecting to www.tortall.net (www.tortall.net)|69.55.226.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1492156 (1,4M) [application/octet-stream]
Saving to: ‘yasm-1.3.0.tar.gz.3’

yasm-1.3.0.tar.gz.3                                         100%[=========================================================================================================================================>]   1,42M   503KB/s    in 2,9s    

2016-10-29 04:52:27 (503 KB/s) - ‘yasm-1.3.0.tar.gz.3’ saved [1492156/1492156]

configure: WARNING: xmlto not found, manpages will not be rebuilt.
ar: `u' modifier ignored since`D' is the default (see `U')
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/simos/.wget-hsts'. HSTS will be disabled.
--2016-10-29 04:52:29--  http://download.videolan.org/pub/x264/snapshots/last_x264.tar.bz2
Resolving download.videolan.org (download.videolan.org)... 88.191.250.2
Connecting to download.videolan.org (download.videolan.org)|88.191.250.2|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 732999 (716K) [application/octet-stream]
Saving to: ‘last_x264.tar.bz2.3’

last_x264.tar.bz2.3                                         100%[=========================================================================================================================================>] 715,82K   778KB/s    in 0,9s    

2016-10-29 04:52:30 (778 KB/s) - ‘last_x264.tar.bz2.3’ saved [732999/732999]

filters/video/resize.c: In function ‘pick_closest_supported_csp’:
filters/video/resize.c:212:9: warning: ‘depth_minus1’ is deprecated [-Wdeprecated-declarations]
         if( pix_desc->comp[i].depth_minus1 >= 8 )
         ^~
In file included from filters/video/resize.c:46:0:
/usr/include/x86_64-linux-gnu/libavutil/pixdesc.h:65:30: note: declared here
     attribute_deprecated int depth_minus1;
                              ^~~~~~~~~~~~
input/lavf.c: In function ‘read_frame_internal’:
input/lavf.c:104:17: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
                 av_free_packet( &pkt );
                 ^~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:318:0,
                 from input/lavf.c:30:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4040:6: note: declared here
 void av_free_packet(AVPacket _pkt);
      ^~~~~~~~~~~~~~
/usr/bin/ld: libx264.a(cabac-a.o): relocation R_X86_64_32 against symbol `x264_cabac_range_lps' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libx264.a(quant-a.o): relocation R_X86_64_32 against hidden symbol`x264_pb_01' can not be used when making a shared object
/usr/bin/ld: libx264.a(dct-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_8000' can not be used when making a shared object
/usr/bin/ld: libx264.a(deblock-a.o): relocation R_X86_64_32 against hidden symbol`x264_pb_1' can not be used when making a shared object
/usr/bin/ld: libx264.a(mc-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_64' can not be used when making a shared object
/usr/bin/ld: libx264.a(mc-a2.o): relocation R_X86_64_32 against hidden symbol`x264_pw_32' can not be used when making a shared object
/usr/bin/ld: libx264.a(pixel-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_00ff' can not be used when making a shared object
/usr/bin/ld: libx264.a(predict-a.o): relocation R_X86_64_32 against hidden symbol`x264_pb_1' can not be used when making a shared object
/usr/bin/ld: libx264.a(dct-64.o): relocation R_X86_64_32 against hidden symbol `x264_hsub_mul' can not be used when making a shared object
/usr/bin/ld: libx264.a(sad-a.o): relocation R_X86_64_32 against hidden symbol`x264_pw_8' can not be used when making a shared object
/usr/bin/ld: libx264.a(trellis-64.o): relocation R_X86_64_32 against symbol `x264_cabac_entropy' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *_\* [x264] Error 1
`
[log.txt](https://github.com/lutris/ffmpeg-nvenc/files/559693/log.txt)

**Comment by Guimli** [comment]
Add -enable-pic --enable-shared after .configure in x264 section :

line 105 :
`./configure --prefix="$build_dir" --bindir="$bin_dir" --enable-pic --enable-shared # --enable-static`

**Comment by Snuggle** [comment]
This fixed the issue for me on Ubuntu 16.10. Thanks so much, Guimli!

**Comment by AmmarkoV** [comment]
Thanks @Guimli :+1:

**Comment by aggresss** [comment]
"--enable-pic" can solve the problem

**Comment by GUOWEIJUN** [comment]
hello,I used homer to find Arabidposis DAN motif,but there are some error ,I am a beginner and don't understand this,so can someone help me, thank you!

 perl /home/guowj/miniconda3/envs/py2/share/homer-4.10-0/configureHomer.pl -list

Current base directory for HOMER is /home/guowj/miniconda3/envs/py2/share/homer-4.10-0/
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/guowj/.wget-hsts'. HSTS will be disabled.
--2019-09-06 12:31:35--  http://homer.ucsd.edu/homer/update.txt
