### ISSUE TITLE
SSR support typo in build.sh

### ISSUE THREAD

**Issue by isilanes** [lutris/ffmpeg-nvenc#6]
In line 225 of build.sh we execute "./configure" within the "build" subdirectory we just created within the clone from https://github.com/MaartenBaert/ssr.git. But shouldn't it be "../configure", as we are not in the main dir where the configure script resides, but rather in a subdir we just created?

**Comment by strycore** [comment]
Sorry, I had taken this whole SSR thing on a sketchy fork of the project on GitHub when I had no intentions of using it, testing it or supporting it.

SSR support has now been removed.
